### PR TITLE
Address #17

### PR DESCRIPTION
**Pull request by seanturner**
Addresses #17.

### CODE REVIEW

**Comment by jakemas** [comment]
Fixed merge conflict. @seanturner can you confirm that I addressed the conflict in the way you would have intended? If so, then I will merge!

**Comment by seanturner** [comment]
@jakemas belatedly lgtm!

**Comment by jakemas** [comment]
Thank you! If that’s all the changes merged, I can release a new WG version ahead of the weekend.

Cheers,
Jake

From: Sean Turner ***@***.***>
Reply-To: lamps-wg/dilithium-certificates ***@***.***>
Date: Friday, July 19, 2024 at 12:03 PM
To: lamps-wg/dilithium-certificates ***@***.***>
Cc: "Massimo, Jake" ***@***.***>, Mention ***@***.***>
Subject: Re: [lamps-wg/dilithium-certificates] Address #17 (PR #18)


@jakemas<https://github.com/jakemas> belatedly lgtm!

**Comment by seanturner** [comment]
Feel free to spin a new version when you get chance.

**Comment by jakemas** [comment]
I did try late Friday night to give you an official version over the weekend (see release 4). But it seems the github workflow has broken, and it wasn’t uploading the new releases. I pulled in new version of the github template we are using, but it didn’t fix the issue. :(

From: Sean Turner ***@***.***>
Reply-To: lamps-wg/dilithium-certificates ***@***.***>
Date: Monday, July 22, 2024 at 10:25 AM
To: lamps-wg/dilithium-certificates ***@***.***>
Cc: "Massimo, Jake" ***@***.***>, Mention ***@***.***>
Subject: Re: [lamps-wg/dilithium-certificates] Address #17 (PR #18)


Feel free to spin a new version when you get chance.

**Comment by seanturner** [comment]
The submission window was closed until Saturday (or maybe Sunday).  Hopefully you can just retry and it'll work.

**Comment by jakemas** [comment]
Ahh okay! Looks like it’s still not opened (https://github.com/lamps-wg/dilithium-certificates/actions/runs/10018760275) but I will keep trying!

From: Sean Turner ***@***.***>
Reply-To: lamps-wg/dilithium-certificates ***@***.***>
Date: Monday, July 22, 2024 at 10:37 AM
To: lamps-wg/dilithium-certificates ***@***.***>
Cc: "Massimo, Jake" ***@***.***>, Mention ***@***.***>
Subject: Re: [lamps-wg/dilithium-certificates] Address #17 (PR #18)


The submission window was closed until Saturday (or maybe Sunday). Hopefully you can just retry and it'll work.

**Comment by jakemas** [comment]
Got it!

From: Sean Turner ***@***.***>
Reply-To: lamps-wg/dilithium-certificates ***@***.***>
Date: Monday, July 22, 2024 at 10:37 AM
To: lamps-wg/dilithium-certificates ***@***.***>
Cc: "Massimo, Jake" ***@***.***>, Mention ***@***.***>
Subject: Re: [lamps-wg/dilithium-certificates] Address #17 (PR #18)


The submission window was closed until Saturday (or maybe Sunday). Hopefully you can just retry and it'll work.

**Pull request merged**
